<a href="https://colab.research.google.com/github/suramshivamani/AIML-2025/blob/main/feature%20scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import preprocessing

In [3]:
x=np.array([[1., -1, 2.],
            [2., 0., 0.],
            [0., 1., -1.]])

In [11]:
x_scaled=preprocessing.scale(x)
x_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [5]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [6]:
x_scaled.std(axis=0)

array([1., 1., 1.])

In [10]:
from sklearn import preprocessing
# Create a StandardScaler instance and assign it to the scaler variable
scaler = preprocessing.StandardScaler()
scaler.fit(x)
scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [12]:
x_test=[1,1,0]
scaler.transform([x_test])

array([[ 0.        ,  1.22474487, -0.26726124]])